### PR TITLE
[WIP] Improve graphics

### LINKED ISSUE #5: Switch to 1D texture for the shadow map

### PR DESCRIPTION
**Pull request by Bastacyclop**
Fixes #5.

### CODE REVIEW

**Comment by Bastacyclop** [comment]
@homu retry

**Comment by Bastacyclop** [comment]
@homu r+

**Comment by Bastacyclop** [comment]
@homusloth r+

**Comment by ghost** [comment]
:pushpin: Commit 2615682 has been approved by `Bastacyclop`

**Comment by ghost** [comment]
:hourglass: Testing commit 2615682 with merge 6f257f3...

**Comment by ghost** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/lazybox/lazybox/builds/157453788)

**Comment by ghost** [comment]
:pushpin: Commit 96649df has been approved by `Bastacyclop`

**Comment by ghost** [comment]
:hourglass: Testing commit 96649df with merge 43a3fe2...

**Comment by Bastacyclop** [comment]
@homusloth retry clean

**Comment by ghost** [comment]
:zap: Test exempted: merge already tested by Travis CI.

**Pull request merged**
