### PR TITLE
Implement settings

### PR DESCRIPTION
**Pull request by Bastacyclop**
Towards #1.

### CODE REVIEW

**Comment by Liotitch** [comment]
@homusloth r+

**Comment by Liotitch** [comment]
@homusloth r+

**Comment by homusloth** [comment]
:pushpin: Commit 82e950c has been approved by `Liotitch`

**Comment by Bastacyclop** [comment]
@homusloth r+

**Comment by homusloth** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by homusloth** [comment]
:pushpin: Commit 82e950c has been approved by `Bastacyclop`

**Comment by Bastacyclop** [comment]
@homusloth retry

**Comment by Bastacyclop** [comment]
@homusloth force clean r+

**Comment by homusloth** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by homusloth** [comment]
:pushpin: Commit 82e950c has been approved by `Bastacyclop`

**Comment by Bastacyclop** [comment]
@homusloth rollup

**Comment by Bastacyclop** [comment]
@homusloth r-

**Comment by Bastacyclop** [comment]
@homusloth r+

**Comment by homusloth** [comment]
:pushpin: Commit 82e950c has been approved by `Bastacyclop`

**Comment by Bastacyclop** [comment]
@homusloth r+

**Comment by homusloth** [comment]
:pushpin: Commit debfcc9 has been approved by `Bastacyclop`

**Pull request merged**
